if get_option('nvidia-oem-properties').allowed()
    # Mapping from option key name to schemas that should be installed if that option is enabled
    schemas = [
        'NvidiaCPER_v1.xml',
        'NvidiaChassis_v1.xml',
        'NvidiaComputerSystem_v1.xml',
        'NvidiaCondition_v1.xml',
        'NvidiaDebugToken_v1.xml',
        'NvidiaDebugTokenManagement_v1.xml',
        'NvidiaEnvironmentMetrics_v1.xml',
        'NvidiaErrorInjection_v1.xml',
        'NvidiaEvent_v1.xml',
        'NvidiaFirmwarePackageCollection_v1.xml',
        'NvidiaFirmwarePackage_v1.xml',
        'NvidiaHistogramBucketCollection_v1.xml',
        'NvidiaHistogramBucket_v1.xml',
        'NvidiaHistogramBuckets_v1.xml',
        'NvidiaHistogramCollection_v1.xml',
        'NvidiaHistogram_v1.xml',
        'NvidiaLogEntry_v1.xml',
        'NvidiaLogService_v1.xml',
        'NvidiaManagedEntityCollection_v1.xml',
        'NvidiaManagedEntityGroupCollection_v1.xml',
        'NvidiaManagedEntityGroup_v1.xml',
        'NvidiaManagedEntity_v1.xml',
        'NvidiaManager_v1.xml',
        'NvidiaMemoryMetrics_v1.xml',
        'NvidiaMemory_v1.xml',
        'NvidiaMetricReport_v1.xml',
        'NvidiaNVLinkMetrics_v1.xml',
        'NvidiaNetworkAdapter_v1.xml',
        'NvidiaNetworkProtocol_v1.xml',
        'NvidiaPCIeEqualization_v1.xml',
        'NvidiaPCIeDevice_v1.xml',
        'NvidiaPCIeSlots_v1.xml',
        'NvidiaPersistentStorage_v1.xml',
        'NvidiaPolicyCollection_v1.xml',
        'NvidiaPolicy_v1.xml',
        'NvidiaPortMetrics_v1.xml',
        'NvidiaPort_v1.xml',
        'NvidiaPowerComplianceManager_v1.xml',
        'NvidiaPowerDomainCollection_v1.xml',
        'NvidiaPowerDomain_v1.xml',
        'NvidiaPSURedundancy_v1.xml',
        'NvidiaPowerPolicyCollection_v1.xml',
        'NvidiaPowerPolicy_v1.xml',
        'NvidiaPowerSmoothingPresetProfileCollection_v1.xml',
        'NvidiaPowerSmoothingPresetProfile_v1.xml',
        'NvidiaPowerSmoothing_v1.xml',
        'NvidiaPowerStateGroup_v1.xml',
        'NvidiaProcessorMetrics_v1.xml',
        'NvidiaProcessorResetMetrics_v1.xml',
        'NvidiaProcessor_v1.xml',
        'NvidiaPscStateCollection_v1.xml',
        'NvidiaPscState_v1.xml',
        'NvidiaPsuStateCollection_v1.xml',
        'NvidiaPsuState_v1.xml',
        'NvidiaRoTChassis_v1.xml',
        'NvidiaRoTImageSlotCollection_v1.xml',
        'NvidiaRoTImageSlot_v1.xml',
        'NvidiaRoTProtectedComponentCollection_v1.xml',
        'NvidiaRoTProtectedComponent_v1.xml',
        'NvidiaSoftwareInventory_v1.xml',
        'NvidiaSwitchPowerMode_v1.xml',
        'NvidiaSwitch_v1.xml',
        'NvidiaSystemConfigProfileStatus_v1.xml',
        'NvidiaSystemConfigProfile_v1.xml',
        'NvidiaSystemProfileCollection_v1.xml',
        'NvidiaSystemProfileFile_v1.xml',
        'NvidiaSystemProfile_v1.xml',
        'NvidiaUpdateService_v1.xml',
        'NvidiaWorkloadPowerProfileCollection_v1.xml',
        'NvidiaWorkloadPowerProfile_v1.xml',
        'NvidiaWorkloadPower_v1.xml',
    ]

    foreach schema : schemas
        install_data(
            'csdl/@0@'.format(schema),
            install_dir: '/usr/share/www/redfish/v1/schema',
        )
    endforeach
endif
